version: "3.9"

services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    expose:
      - "6379"
    command: redis-server

  app:
    build: ./app
    container_name: app
    restart: always
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate  &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
