# Generated by Django 4.1.5 on 2023-01-31 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sea", "0002_rename_score_scoreboardmodel"),
    ]

    operations = [
        migrations.DeleteModel(name="ScoreBoardModel",),
    ]
