# Generated by Django 4.1.5 on 2023-03-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameHistoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player1", models.CharField(max_length=100)),
                ("player2", models.CharField(max_length=100)),
                ("win", models.CharField(blank=True, max_length=100, null=True)),
                ("left", models.CharField(blank=True, max_length=100, null=True)),
                ("time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
