# Generated by Django 4.1.5 on 2023-03-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamehistorymodel",
            name="player1",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="gamehistorymodel",
            name="player2",
            field=models.CharField(max_length=100),
        ),
    ]
